$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: custom-deployment
endpoint_name: mycustom-endpoint
model:
  name: my-python-object
  version: 1
  path: ./pyobject
environment_variables:
  MODEL_BASE_PATH: /var/azureml-app/azureml-models/my-dummy-model/1
  MODEL_NAME: my-dummy-model
environment:
  image: <ACR_NAME>.azurecr.io/flasml:latest
  inference_config:
    liveness_route:
      port: 3000
      path: /am/alive
    readiness_route:
      port: 3000
      path: /am/ready
    scoring_route:
      port: 3000
      path: /score
instance_type: Standard_DS2_v2
instance_count: 1